id: I88977D82
initial_creation_type: ebook
source_metadata:
  id: RDI-SS-37
  title: 1) དཀོན་མཆོག་སྤྱི་འདུས་ཀྱི་ཁྲིད་ཡིག་གུ་རུའི་དགོངས་རྒྱན་ཉིན་བྱེད་རྙིང་པོའི་རྫོགས་རིམ་སྐོར་གྱི་ཟབ་ཁྲིད།
  author: མཛད་པ་པོ།སི་ཏུ་པདྨ་ཉིན་བྱེད་དབང་པོ།, མཛད་པ་པོ།འཇམ་མགོན་ཀོང་སྤྲུལ་བློ་གྲོས་མཐས་ཡས།,
    4) བཀའ་གསང་རྫོགས་པ་ཆེན་པོ་དཀོན་མཆོག་སྤྱི་འདུས་ཀྱི་ཁྲིད་ཡིག་མན་ངག་གསལ་སྒྲོན་སྙིང་པོ།,
    མཛད་པ་པོ། མི་འགྱུར་དཔལ་སྒྲོན།
  authors: &id001
  - མཛད་པ་པོ།སི་ཏུ་པདྨ་ཉིན་བྱེད་དབང་པོ།
  - མཛད་པ་པོ།འཇམ་མགོན་ཀོང་སྤྲུལ་བློ་གྲོས་མཐས་ཡས།
  - 4) བཀའ་གསང་རྫོགས་པ་ཆེན་པོ་དཀོན་མཆོག་སྤྱི་འདུས་ཀྱི་ཁྲིད་ཡིག་མན་ངག་གསལ་སྒྲོན་སྙིང་པོ།
  - མཛད་པ་པོ། མི་འགྱུར་དཔལ་སྒྲོན།
  sku: RDI-SS-37
  cover: RDI-SS-37.jpg
  volume: {}
ebook_metadata:
  title: 1) དཀོན་མཆོག་སྤྱི་འདུས་ཀྱི་ཁྲིད་ཡིག་གུ་རུའི་དགོངས་རྒྱན་ཉིན་བྱེད་རྙིང་པོའི་རྫོགས་རིམ་སྐོར་གྱི་ཟབ་ཁྲིད།
  authors: *id001
  sku: RDI-SS-37
  cover: RDI-SS-37.jpg
layers:
- Author
- BookTitle
- Chapter
- Citation
- Commentary
- Sabche
- Tsawa
