id: I88977D82
initial_creation_type: ebook
source_metadata:
  id: RDI-SS-37
  title: དཀོན་མཆོག་སྤྱི་འདུས་འགྲེལ་བ་གཅེས་བཏུས།
  author: མཛད་པ་པོ།སི་ཏུ་པདྨ་ཉིན་བྱེད་དབང་པོ།, མཛད་པ་པོ།འཇམ་མགོན་ཀོང་སྤྲུལ་བློ་གྲོས་མཐས་ཡས།,
    མཛད་པ་པོ། མི་འགྱུར་དཔལ་སྒྲོན།
  authors: &id001
  - མཛད་པ་པོ།སི་ཏུ་པདྨ་ཉིན་བྱེད་དབང་པོ།
  - མཛད་པ་པོ།འཇམ་མགོན་ཀོང་སྤྲུལ་བློ་གྲོས་མཐས་ཡས།
  - མཛད་པ་པོ། མི་འགྱུར་དཔལ་སྒྲོན།
  sku: RDI-SS-37
  cover: RDI-SS-37.jpg
  volume: {}
  title_source: epub:dc:title:ambiguous-layer
ebook_metadata:
  title: དཀོན་མཆོག་སྤྱི་འདུས་འགྲེལ་བ་གཅེས་བཏུས།
  authors: *id001
  sku: RDI-SS-37
  cover: RDI-SS-37.jpg
layers:
- Author
- BookTitle
- Chapter
- Citation
- Commentary
- Sabche
- Tsawa
